### ISSUE TITLE
Text outside box.

### ISSUE THREAD

**Issue by SuperOrca** [TeamMH/minehutxyz#13]
![image](https://user-images.githubusercontent.com/70454918/94565350-17c25280-0237-11eb-829b-95fcb8e073f2.png)

**Comment by TeamMH** [comment]
We'll work on using smaller descriptions, I'll edit these ones now. If you find any other issues with this please send a screenshot in this same issue. ❤

**Comment by untitledgeese** [comment]
Issue resolved, closing
