### ISSUE TITLE
Add less tags to the sidebar

### ISSUE THREAD

**Issue by LukasmanMHdude** [TeamMH/minehutxyz#2]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website (design)

**Describe the feature**
Adde better navigation to the sidebar. Not sure if this is possible, but instead of just listing plugin tuts, go ahead and add a place to search for them. also, limit "popular questions" to 5 or 6 commonly asked ones, then have another page with all of them (and a search). 

**How the feature is useful**
This would help navigation on the platform.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by TeamMH** [comment]
It's impossible to modify how many tags appear on the sidebar and make a search because Gitbook doesn't allow it
