### ISSUE TITLE
Add downloads for skripts to all the examples

### ISSUE THREAD

**Issue by LukasmanMHdude** [TeamMH/minehutxyz#43]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Add full downloads of skripts from the examples folder. I will do this btw, but I would like to get feedback from everyone first.

**How the feature is useful**
Gives people a full version to look at

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
I feel like it's a bit useless considered most of the examples are very short. If we offer more in depth examples, we can certainly do this.

**Comment by LukasmanMHdude** [comment]
These are meant to be more of raw files rather than an actual Mediafire download link.

**Comment by LukasmanMHdude** [comment]
added in #51
