### ISSUE TITLE
How to upload datapacks to minehut

### ISSUE THREAD

**Issue by LukasmanMHdude** [TeamMH/minehutxyz#46]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Describe the article**
Would show people how to upload data packs, as well as a link to the minehut video tutorial.

**How the article is useful**
"Can we upload data packs" in a common question because you couldn't do it in the past and it's very hard.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
Completed, [[view](https://minehut.xyz/faq/panel/datapacks)]
