### ISSUE TITLE
Multiverse tutorial

### ISSUE THREAD

**Issue by LukasmanMHdude** [TeamMH/minehutxyz#48]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Describe the article**
A tut on how to use multiverse basic commands, as well as how to use VoidGenerator with multiverse.

**How the article is useful**
Helps people who don't know how to use multiverse, and instead of looking up endless youtube videos.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
This tutorial was already made 3 weeks ago, [[view](https://minehut.xyz/plugin/popular/multiverse)]
