### ISSUE TITLE
How to create a server

### ISSUE THREAD

**Issue by LukasmanMHdude** [TeamMH/minehutxyz#49]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Describe the article**
This would show you were on the panel to make a server

**How the article is useful**
Helps people new to minehut.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
We have a full Minehut tutorial, [[view](https://minehut.xyz/faq/minehut/full)]
