### ISSUE TITLE
One Player Sleep Skript

### ISSUE THREAD

**Issue by AdxmGG** [TeamMH/minehutxyz#52]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Describe the article**

Explain and code a one player sleep skript.
**How the article is useful**

help server owners who want this skript.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment]
I personally think this would be better as a command block tutorial (its only 1 command block lol)

**Comment by AdxmGG** [comment]
Article Made, [[view](https://minehut.xyz/skript/examples/sleep)]
