### ISSUE TITLE
Custom /help Tutorial (SKRIPT)

### ISSUE THREAD

**Issue by Centrect** [TeamMH/minehutxyz#56]
### Feature request

**Checklist**
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Describe the article**

A tutorial on how to make a custom /help, would help player's making servers where they need large amounts of information from a single command.

**How the article is useful**

Helps people who want to make a custom /help command

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by AdxmGG** [comment]
Will make tomorrow.

**Comment by LukasmanMHdude** [comment]
I'm not sure how this would be structured. are you thinking of a function or smth that they can easily use or bassilclly just like a 
```vb
command /help <integer>:
  trigger:
    if arg 1 is "1"
      message "text"
```
and so on or some complicated function?

**Comment by AdxmGG** [comment]
Completed, [[view](https://minehut.xyz/skript/examples/help)]
