### ISSUE TITLE
Misspelling of "API Documentation"

### ISSUE THREAD

**Issue by ahoulton** [TeamMH/minehutxyz#58]
### Bug Report

**Checklist**
- [X] I am NOT reporting a security vulnerability
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information

**Platform**
Website.

**To reproduce**
Go to the website and find that the "API Documentation" is misspelt.

Steps to reproduce the behaviour:
1. Go to Website.
2. Look at the sidebar.
3. See error.

**Expected behaviour**
It should show "API Documentation" and not "API Documenation"

**Screenshots**
N/A

**Additional context**
N/A

---
**Try to reproduce this bug and let us know in the comments if you can reproduce it or not. Make sure to include your relevant device information!**

**Comment by LukasmanMHdude** [comment]
You could have made this a pull instead of an issue, but thx!

**Comment by tarna** [comment]
It's been fixed. Thanks for letting us now. 

Blame Adam

**Comment by ahoulton** [comment]
> You could have made this a pull instead of an issue, but thx!

I'm kinda too lazy to do it right now since I have to relearn GitBook and setup the development env.

**Comment by LukasmanMHdude** [comment]
Uh why ^

**Comment by ahoulton** [comment]
> Uh why ^

It makes sense if comments were locked since the issue got resolved, would avoid people from commenting on stuff that has already been fixed/added.
